import type { LawUniversity } from './types';

/**
 * Türkiye hukuk fakülteleri — YALNIZCA YÖK Atlas / ÖSYM’de Hukuk programı
 * görünen (veya fiilen öğrenci alan) TR kampüsleri.
 *
 * Kaynak: 2025–2026 YKS yerleştirme / YÖK Atlas sentezi (universitetercihrobotu
 * derlemesi + çapraz kontrol). KKTC ve yurt dışı satırlar bu listede yok.
 *
 * KURAL: “Her şehir” değil — “her hukuk fakültesi”. Hukuk fakültesi olmayan
 * üniversite (Ağrı, Van YYÜ planı, Ege planı vb.) active:false veya listede yok.
 *
 * Son doğrulama: 2026-08-05
 */
export const LAW_UNIVERSITIES: LawUniversity[] = [
  // —— Öncelik 1: yüksek arama hacmi / köklü ——
  {
    slug: 'ankara-yildirim-beyazit',
    name: 'Ankara Yıldırım Beyazıt Üniversitesi Hukuk Fakültesi',
    shortName: 'AYBÜ',
    city: 'Ankara',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['yıldırım beyazıt hukuk', 'aybü hukuk', 'yildirim beyazit hukuk'],
    active: true,
    priority: 1,
  },
  {
    slug: 'ankara',
    name: 'Ankara Üniversitesi Hukuk Fakültesi',
    shortName: 'AÜHF',
    city: 'Ankara',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['ankara hukuk', 'aühf'],
    active: true,
    priority: 1,
  },
  {
    slug: 'istanbul',
    name: 'İstanbul Üniversitesi Hukuk Fakültesi',
    shortName: 'İÜHF',
    city: 'İstanbul',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['istanbul hukuk', 'iühf', 'beyazıt hukuk'],
    active: true,
    priority: 1,
  },
  {
    slug: 'marmara',
    name: 'Marmara Üniversitesi Hukuk Fakültesi',
    shortName: 'MÜHF',
    city: 'İstanbul',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['marmara hukuk'],
    active: true,
    priority: 1,
  },
  {
    slug: 'galatasaray',
    name: 'Galatasaray Üniversitesi Hukuk Fakültesi',
    shortName: 'GSÜ',
    city: 'İstanbul',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'fr',
    aliases: ['galatasaray hukuk', 'gsü hukuk'],
    active: true,
    priority: 1,
    notes: 'Fransızca ağırlıklı izlence; mehaz Fransa etkisi',
  },
  {
    slug: 'dokuz-eylul',
    name: 'Dokuz Eylül Üniversitesi Hukuk Fakültesi',
    shortName: 'DEÜ',
    city: 'İzmir',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['dokuz eylül hukuk', 'deu hukuk'],
    active: true,
    priority: 1,
  },
  {
    slug: 'hacettepe',
    name: 'Hacettepe Üniversitesi Hukuk Fakültesi',
    shortName: 'Hacettepe',
    city: 'Ankara',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['hacettepe hukuk'],
    active: true,
    priority: 1,
  },
  {
    slug: 'ankara-hacibayram',
    name: 'Ankara Hacı Bayram Veli Üniversitesi Hukuk Fakültesi',
    shortName: 'AHBV',
    city: 'Ankara',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['hacı bayram hukuk', 'gazi hukuk', 'ahbv hukuk'],
    active: true,
    priority: 1,
  },
  {
    slug: 'bilkent',
    name: 'İhsan Doğramacı Bilkent Üniversitesi Hukuk Fakültesi',
    shortName: 'Bilkent',
    city: 'Ankara',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr-en30',
    aliases: ['bilkent hukuk'],
    active: true,
    priority: 1,
  },
  {
    slug: 'koc',
    name: 'Koç Üniversitesi Hukuk Fakültesi',
    shortName: 'Koç',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr-en30',
    aliases: ['koç hukuk', 'koc hukuk'],
    active: true,
    priority: 1,
  },
  {
    slug: 'tobb-etu',
    name: 'TOBB Ekonomi ve Teknoloji Üniversitesi Hukuk Fakültesi',
    shortName: 'TOBB ETÜ',
    city: 'Ankara',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr-en30',
    aliases: ['tobb hukuk', 'tobb etü hukuk'],
    active: true,
    priority: 1,
  },
  {
    slug: 'bogazici',
    name: 'Boğaziçi Üniversitesi Hukuk Fakültesi',
    shortName: 'BÜ',
    city: 'İstanbul',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['boğaziçi hukuk'],
    active: true,
    priority: 1,
  },
  {
    slug: 'ozyegin',
    name: 'Özyeğin Üniversitesi Hukuk Fakültesi',
    shortName: 'Özyeğin',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr-en30',
    aliases: ['özyeğin hukuk'],
    active: true,
    priority: 1,
  },
  {
    slug: 'yeditepe',
    name: 'Yeditepe Üniversitesi Hukuk Fakültesi',
    shortName: 'Yeditepe',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr-en30',
    aliases: ['yeditepe hukuk'],
    active: true,
    priority: 1,
  },

  // —— Öncelik 2: büyük şehir / bilinen ——
  {
    slug: 'akdeniz',
    name: 'Akdeniz Üniversitesi Hukuk Fakültesi',
    shortName: 'Akdeniz',
    city: 'Antalya',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['akdeniz hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'selcuk',
    name: 'Selçuk Üniversitesi Hukuk Fakültesi',
    shortName: 'Selçuk',
    city: 'Konya',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['selçuk hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'erciyes',
    name: 'Erciyes Üniversitesi Hukuk Fakültesi',
    shortName: 'Erciyes',
    city: 'Kayseri',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['erciyes hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'uludag',
    name: 'Bursa Uludağ Üniversitesi Hukuk Fakültesi',
    shortName: 'Uludağ',
    city: 'Bursa',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['uludağ hukuk', 'bursa hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'cukurova',
    name: 'Çukurova Üniversitesi Hukuk Fakültesi',
    shortName: 'Çukurova',
    city: 'Adana',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['çukurova hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'anadolu',
    name: 'Anadolu Üniversitesi Hukuk Fakültesi',
    shortName: 'Anadolu',
    city: 'Eskişehir',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['anadolu hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'asbu',
    name: 'Ankara Sosyal Bilimler Üniversitesi Hukuk Fakültesi',
    shortName: 'ASBÜ',
    city: 'Ankara',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['asbü hukuk', 'sosyal bilimler hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'istanbul-medeniyet',
    name: 'İstanbul Medeniyet Üniversitesi Hukuk Fakültesi',
    shortName: 'Medeniyet',
    city: 'İstanbul',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['medeniyet hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'bahcesehir',
    name: 'Bahçeşehir Üniversitesi Hukuk Fakültesi',
    shortName: 'BAU',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr-en30',
    aliases: ['bahçeşehir hukuk', 'bau hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'kadir-has',
    name: 'Kadir Has Üniversitesi Hukuk Fakültesi',
    shortName: 'KHAS',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr-en30',
    aliases: ['kadir has hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'istanbul-bilgi',
    name: 'İstanbul Bilgi Üniversitesi Hukuk Fakültesi',
    shortName: 'Bilgi',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr-en30',
    aliases: ['bilgi üniversitesi hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'medipol',
    name: 'İstanbul Medipol Üniversitesi Hukuk Fakültesi',
    shortName: 'Medipol',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['medipol hukuk', 'istanbul medipol hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'altinbas',
    name: 'Altınbaş Üniversitesi Hukuk Fakültesi',
    shortName: 'Altınbaş',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['altınbaş hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'maltepe',
    name: 'Maltepe Üniversitesi Hukuk Fakültesi',
    shortName: 'Maltepe',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['maltepe hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'dogus',
    name: 'Doğuş Üniversitesi Hukuk Fakültesi',
    shortName: 'Doğuş',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['doğuş hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'okan',
    name: 'İstanbul Okan Üniversitesi Hukuk Fakültesi',
    shortName: 'Okan',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['okan hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'kultur',
    name: 'İstanbul Kültür Üniversitesi Hukuk Fakültesi',
    shortName: 'İKÜ',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['kültür üniversitesi hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'aydin',
    name: 'İstanbul Aydın Üniversitesi Hukuk Fakültesi',
    shortName: 'İAÜ',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['aydın üniversitesi hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'beykent',
    name: 'Beykent Üniversitesi Hukuk Fakültesi',
    shortName: 'Beykent',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['beykent hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'fatih-sultan',
    name: 'Fatih Sultan Mehmet Vakıf Üniversitesi Hukuk Fakültesi',
    shortName: 'FSMVÜ',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['fsm hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'ataturk',
    name: 'Atatürk Üniversitesi Hukuk Fakültesi',
    shortName: 'Atatürk',
    city: 'Erzurum',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['atatürk hukuk', 'erzurum hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'inonu',
    name: 'İnönü Üniversitesi Hukuk Fakültesi',
    shortName: 'İnönü',
    city: 'Malatya',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['inönü hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'dicle',
    name: 'Dicle Üniversitesi Hukuk Fakültesi',
    shortName: 'Dicle',
    city: 'Diyarbakır',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['dicle hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'gaziantep',
    name: 'Gaziantep Üniversitesi Hukuk Fakültesi',
    shortName: 'GAÜN',
    city: 'Gaziantep',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['gaziantep hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'suleyman-demirel',
    name: 'Süleyman Demirel Üniversitesi Hukuk Fakültesi',
    shortName: 'SDÜ',
    city: 'Isparta',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['sdu hukuk', 'isparta hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'pamukkale',
    name: 'Pamukkale Üniversitesi Hukuk Fakültesi',
    shortName: 'PAÜ',
    city: 'Denizli',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['pamukkale hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'sakarya',
    name: 'Sakarya Üniversitesi Hukuk Fakültesi',
    shortName: 'SAÜ',
    city: 'Sakarya',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['sakarya hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'kocaeli',
    name: 'Kocaeli Üniversitesi Hukuk Fakültesi',
    shortName: 'KOÜ',
    city: 'Kocaeli',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['kocaeli hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'balikesir',
    name: 'Balıkesir Üniversitesi Hukuk Fakültesi',
    shortName: 'BAÜN',
    city: 'Balıkesir',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['balıkesir hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'afyon',
    name: 'Afyon Kocatepe Üniversitesi Hukuk Fakültesi',
    shortName: 'AKÜ',
    city: 'Afyonkarahisar',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['afyon hukuk', 'kocatepe hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'eskisehir-osmangazi',
    name: 'Eskişehir Osmangazi Üniversitesi Hukuk Fakültesi',
    shortName: 'ESOGÜ',
    city: 'Eskişehir',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['osmangazi hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'sivas-cumhuriyet',
    name: 'Sivas Cumhuriyet Üniversitesi Hukuk Fakültesi',
    shortName: 'SCÜ',
    city: 'Sivas',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['cumhuriyet hukuk', 'sivas hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'samsun',
    name: 'Ondokuz Mayıs Üniversitesi Hukuk Fakültesi',
    shortName: 'OMÜ',
    city: 'Samsun',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['ondokuz mayıs hukuk', 'samsun hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'erzincan',
    name: 'Erzincan Binali Yıldırım Üniversitesi Hukuk Fakültesi',
    shortName: 'EBYÜ',
    city: 'Erzincan',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['erzincan hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'kirikkale',
    name: 'Kırıkkale Üniversitesi Hukuk Fakültesi',
    shortName: 'Kırıkkale',
    city: 'Kırıkkale',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['kırıkkale hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'necmettin-erbakan',
    name: 'Necmettin Erbakan Üniversitesi Hukuk Fakültesi',
    shortName: 'NEÜ',
    city: 'Konya',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['necmettin erbakan hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'atilim',
    name: 'Atılım Üniversitesi Hukuk Fakültesi',
    shortName: 'Atılım',
    city: 'Ankara',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['atılım hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'cankaya',
    name: 'Çankaya Üniversitesi Hukuk Fakültesi',
    shortName: 'Çankaya',
    city: 'Ankara',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['çankaya hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'baskent',
    name: 'Başkent Üniversitesi Hukuk Fakültesi',
    shortName: 'Başkent',
    city: 'Ankara',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['başkent hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'yasar',
    name: 'Yaşar Üniversitesi Hukuk Fakültesi',
    shortName: 'Yaşar',
    city: 'İzmir',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['yaşar hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'izmir-ekonomi',
    name: 'İzmir Ekonomi Üniversitesi Hukuk Fakültesi',
    shortName: 'İEÜ',
    city: 'İzmir',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr-en30',
    aliases: ['izmir ekonomi hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'antalya-bilim',
    name: 'Antalya Bilim Üniversitesi Hukuk Fakültesi',
    shortName: 'ABÜ',
    city: 'Antalya',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['antalya bilim hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'hasan-kalyoncu',
    name: 'Hasan Kalyoncu Üniversitesi Hukuk Fakültesi',
    shortName: 'HKÜ',
    city: 'Gaziantep',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['hasan kalyoncu hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'turk-alman',
    name: 'Türk-Alman Üniversitesi Hukuk Fakültesi',
    shortName: 'TAÜ',
    city: 'İstanbul',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['türk alman hukuk', 'tau hukuk'],
    active: true,
    priority: 2,
    notes: 'Almanya mehaz / karşılaştırmalı vurgu',
  },
  {
    slug: 'mef',
    name: 'MEF Üniversitesi Hukuk Fakültesi',
    shortName: 'MEF',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['mef hukuk'],
    active: true,
    priority: 2,
  },
  {
    slug: 'ibn-haldun',
    name: 'İbn Haldun Üniversitesi Hukuk Fakültesi',
    shortName: 'İHÜ',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['ibn haldun hukuk'],
    active: true,
    priority: 2,
  },

  // —— Öncelik 3: diğer doğrulanmış TR programlar ——
  {
    slug: 'tokat',
    name: 'Tokat Gaziosmanpaşa Üniversitesi Hukuk Fakültesi',
    shortName: 'TOGÜ',
    city: 'Tokat',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['tokat hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'yozgat',
    name: 'Yozgat Bozok Üniversitesi Hukuk Fakültesi',
    shortName: 'Bozok',
    city: 'Yozgat',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['bozok hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'rize',
    name: 'Recep Tayyip Erdoğan Üniversitesi Hukuk Fakültesi',
    shortName: 'RTEÜ',
    city: 'Rize',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['rte üniversitesi hukuk', 'rize hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'bolu',
    name: 'Bolu Abant İzzet Baysal Üniversitesi Hukuk Fakültesi',
    shortName: 'BAİBÜ',
    city: 'Bolu',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['abant hukuk', 'bolu hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'cankiri',
    name: 'Çankırı Karatekin Üniversitesi Hukuk Fakültesi',
    shortName: 'Karatekin',
    city: 'Çankırı',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['karatekin hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'tekirdag',
    name: 'Tekirdağ Namık Kemal Üniversitesi Hukuk Fakültesi',
    shortName: 'NKÜ',
    city: 'Tekirdağ',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['namık kemal hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'kirklareli',
    name: 'Kırklareli Üniversitesi Hukuk Fakültesi',
    shortName: 'Kırklareli',
    city: 'Kırklareli',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['kırklareli hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'trabzon',
    name: 'Trabzon Üniversitesi Hukuk Fakültesi',
    shortName: 'Trabzon',
    city: 'Trabzon',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['trabzon hukuk'],
    active: true,
    priority: 3,
    notes: 'KTÜ değil — Trabzon Üniversitesi',
  },
  {
    slug: 'yalova',
    name: 'Yalova Üniversitesi Hukuk Fakültesi',
    shortName: 'Yalova',
    city: 'Yalova',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['yalova hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'izmir-bakircay',
    name: 'İzmir Bakırçay Üniversitesi Hukuk Fakültesi',
    shortName: 'Bakırçay',
    city: 'İzmir',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['bakırçay hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'izmir-demokrasi',
    name: 'İzmir Demokrasi Üniversitesi Hukuk Fakültesi',
    shortName: 'İDÜ',
    city: 'İzmir',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['izmir demokrasi hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'izmir-katip-celebi',
    name: 'İzmir Katip Çelebi Üniversitesi Hukuk Fakültesi',
    shortName: 'İKÇÜ',
    city: 'İzmir',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['katip çelebi hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'ufuk',
    name: 'Ufuk Üniversitesi Hukuk Fakültesi',
    shortName: 'Ufuk',
    city: 'Ankara',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['ufuk hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'ankara-bilim',
    name: 'Ankara Bilim Üniversitesi Hukuk Fakültesi',
    shortName: 'Ankara Bilim',
    city: 'Ankara',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['ankara bilim hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'ankara-medipol',
    name: 'Ankara Medipol Üniversitesi Hukuk Fakültesi',
    shortName: 'Ankara Medipol',
    city: 'Ankara',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['ankara medipol hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'cag',
    name: 'Çağ Üniversitesi Hukuk Fakültesi',
    shortName: 'Çağ',
    city: 'Mersin',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['çağ hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'istanbul-29-mayis',
    name: 'İstanbul 29 Mayıs Üniversitesi Hukuk Fakültesi',
    shortName: '29 Mayıs',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['29 mayıs hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'istanbul-gedik',
    name: 'İstanbul Gedik Üniversitesi Hukuk Fakültesi',
    shortName: 'Gedik',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['gedik hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'istanbul-zaim',
    name: 'İstanbul Sabahattin Zaim Üniversitesi Hukuk Fakültesi',
    shortName: 'İZÜ',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['zaim hukuk', 'sabahattin zaim hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'istanbul-ticaret',
    name: 'İstanbul Ticaret Üniversitesi Hukuk Fakültesi',
    shortName: 'Ticaret',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['ticaret üniversitesi hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'yeni-yuzyil',
    name: 'İstanbul Yeni Yüzyıl Üniversitesi Hukuk Fakültesi',
    shortName: 'Yeni Yüzyıl',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['yeni yüzyıl hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'kto-karatay',
    name: 'KTO Karatay Üniversitesi Hukuk Fakültesi',
    shortName: 'Karatay',
    city: 'Konya',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['karatay hukuk', 'kto hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'nuh-naci-yazgan',
    name: 'Nuh Naci Yazgan Üniversitesi Hukuk Fakültesi',
    shortName: 'NNY',
    city: 'Kayseri',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['nuh naci yazgan hukuk'],
    active: true,
    priority: 3,
  },
  {
    slug: 'piri-reis',
    name: 'Piri Reis Üniversitesi Hukuk Fakültesi',
    shortName: 'Piri Reis',
    city: 'İstanbul',
    type: 'vakif',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['piri reis hukuk'],
    active: true,
    priority: 3,
  },

  // —— Pasif / plan aşaması (SEO’ya açılmasın) ——
  {
    slug: 'van-yyu',
    name: 'Van Yüzüncü Yıl Üniversitesi Hukuk Fakültesi',
    shortName: 'YYÜ',
    city: 'Van',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['yüzüncü yıl hukuk', 'van hukuk fakültesi'],
    active: false,
    priority: 3,
    notes:
      'Kuruluş/plan aşaması; YÖK Atlas’ta öğrenci alan Hukuk programı yok (2025–2026). Not üretilmez.',
  },
  {
    slug: 'ege',
    name: 'Ege Üniversitesi Hukuk Fakültesi',
    shortName: 'Ege',
    city: 'İzmir',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: ['ege hukuk'],
    active: false,
    priority: 3,
    notes: 'Resmi Gazete ile kuruldu; YÖK Atlas’ta henüz yerleştirme programı yoksa pasif.',
  },
  {
    slug: 'agri',
    name: 'Ağrı İbrahim Çeçen Üniversitesi (hukuk fakültesi yok)',
    shortName: 'AİÇÜ',
    city: 'Ağrı',
    type: 'devlet',
    calendar: 'donemlik',
    lang: 'tr',
    aliases: [],
    active: false,
    priority: 3,
    notes: 'Hukuk fakültesi yok — önceki hatalı kayıt; not üretilmez.',
  },
];

export function getActiveUniversities(): LawUniversity[] {
  return LAW_UNIVERSITIES.filter((u) => u.active);
}

export function getUniversityBySlug(slug: string): LawUniversity | undefined {
  return LAW_UNIVERSITIES.find((u) => u.slug === slug && u.active);
}

export function getUniversitiesByPriority(p: 1 | 2 | 3): LawUniversity[] {
  return getActiveUniversities().filter((u) => u.priority === p);
}
