/**
 * AUTO-GENERATED by scripts/build-flavor.mjs — flavor: portal
 * Do not edit by hand; re-run: node scripts/build-flavor.mjs --app=portal
 */
const config = {
  "appId": "com.avfethiguzel.hukuk",
  "appName": "Av. Fethi Güzel",
  "webDir": "www",
  "server": {
    "url": "https://www.avfethiguzel.com/?app=portal&lang=tr&utm_source=android_app&utm_medium=portal",
    "cleartext": false,
    "allowNavigation": [
      "avfethiguzel.com",
      "*.avfethiguzel.com",
      "www.avfethiguzel.com",
      "maps.google.com",
      "*.google.com",
      "play.google.com"
    ]
  },
  "plugins": {
    "SplashScreen": {
      "launchShowDuration": 900,
      "launchAutoHide": true,
      "backgroundColor": "#2E4036",
      "showSpinner": false,
      "androidSplashResourceName": "splash",
      "splashFullScreen": true,
      "splashImmersive": true
    },
    "StatusBar": {
      "style": "DARK",
      "backgroundColor": "#2E4036"
    }
  },
  "android": {
    "allowMixedContent": false,
    "backgroundColor": "#F2F0E9",
    "webContentsDebuggingEnabled": false
  }
} as const;
export default config;
