// Galaxy flavor: icthat
// android/app/build.gradle defaultConfig içine veya productFlavors'a kopyalayın
// applicationId "com.avfethiguzel.icthat"
// versionCode 1
// versionName "1.0.0"
android {
    defaultConfig {
        applicationId "com.avfethiguzel.icthat"
        versionCode 1
        versionName "1.0.0"
        resValue "string", "app_name", "İçtihat Günü"
    }
}
