// Galaxy flavor: portal
// android/app/build.gradle defaultConfig içine veya productFlavors'a kopyalayın
// applicationId "com.avfethiguzel.hukuk"
// versionCode 3
// versionName "1.2.0"
android {
    defaultConfig {
        applicationId "com.avfethiguzel.hukuk"
        versionCode 3
        versionName "1.2.0"
        resValue "string", "app_name", "Av. Fethi Güzel"
    }
}
